### ISSUE TITLE
About return orders

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#223] opened 2020-06-13 10:13 UTC
Do you have no interface for returning orders? Or change the order status is the return order? If yes, please tell me the status of your return order, thank you

**Comment by vietcaominh** [comment] 2020-06-13 10:54
hi @chengbirght ch
Currently, we don't have the endpoint to get return orders (RMA). But we have this on the backlog.
https://github.com/tikivn/open-api-docs/issues/197.
Do you need this urgently? It likely will release the next sprint (in the next 2 weeks). Please stay tuned, we will let you know by then

**Comment by chengbirght** [comment] 2020-06-15 01:17
ok,thanks。Looking forward to your next version

**Comment by vietcaominh** [comment] 2020-06-15 02:53
Thank you for waiting please don't close it for now. We will use it to update you when it released

**Comment by chengbirght** [comment] 2020-06-15 02:54
Okay，thanks

**Comment by hoai-dam** [comment] 2020-08-31 16:33
Duplicate of #197

**Closed by hoai-dam** 2020-08-31 16:33 UTC
Labels: created backlog
