### ISSUE TITLE
Return seller's order revenue

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#130] opened 2020-03-06 08:12 UTC
@ducanhnguyen19 Thank you for your support. Appreciate that! Received inventory information safe and sound. Another request is that for Orders API, are you able to return the seller's revenue for each orders (after tax, commission and other fees deduction). At the moment, I only receive total_price_after_discount which does not factor in all the above fees.

_Originally posted by @kabuky in https://github.com/tikivn/open-api-docs/issues/117#issuecomment-594393231_

**Comment by ducanhnguyen19** [comment] 2020-03-06 08:51
ok, I will tell you once we release this feature

**Comment by vietcaominh** [comment] 2020-05-11 16:21
@ducanhnguyen19 please help create a backlog for it if haven't

**Comment by hoai-dam** [comment] 2020-06-24 08:19
Hello @kabuky ,

We planned to update the orders format returned from the open api endpoints. This update will include seller revenue.
This update is planned for 2 weeks from now.

FYI.

**Comment by kabuky** [comment] 2020-07-02 10:47
Thank you. Looking forward to the update.

**Comment by hoai-dam** [comment] 2020-08-31 16:23
Hello @kabuky ,
We have released the Order API V2 with a better Order payload. This version includes all the customer invoice and seller statement data.

Duplicate of #207

**Closed by hoai-dam** 2020-08-31 16:23 UTC
Labels: is checking
