### ISSUE TITLE
Trả về doanh thu của đơn ordersGet api

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#79] opened 2020-02-06 03:55 UTC
![picturemessage_ofq5fgez qwn](https://user-images.githubusercontent.com/45413747/73904628-38682180-48cf-11ea-946b-8d0ad2f15022.png)

Mình muốn lấy số doanh thu của đơn Tiki trả cho nhà bán, team giúp mình trả về số này nữa được không ạ?

**Comment by hoank92** [comment] 2020-02-07 03:16
Currently the sales of the order is being calculated at the time the seller settlement with TIKI. Current results returned by orders are not correct, we will update and return.

**Comment by vietcaominh** [comment] 2020-05-11 16:25
@hoank92 please help check the status of this

**Comment by tuhucon** [comment] 2020-06-09 04:05
we will create a backlog for this issuse

**Comment by hoai-dam** [comment] 2020-08-31 16:25
Hello @Hungpx ,
We resolved this now by releasing Order API V2. 

Duplicate of #207

**Closed by hoai-dam** 2020-08-31 16:25 UTC
Labels: created backlog
